create database if not exists `av_ecom`;

USE `av_ecom`;

CREATE DATABASE `av_ecom` /*!40100 DEFAULT CHARACTER SET latin1 */;
CREATE TABLE `catentship` (
  `CATENTRY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `WEIGHT` float(5,2) NOT NULL DEFAULT '0.00',
  `WEIGHTMEASURE` char(16) DEFAULT NULL,
  `LENGTH` float(5,2) DEFAULT NULL,
  `WIDTH` float(5,2) DEFAULT NULL,
  `HEIGHT` float(5,2) DEFAULT NULL,
  `SIZEMEASURE` char(16) DEFAULT NULL,
  `NOMINALQUANTITY` float(5,2) NOT NULL DEFAULT '1.00',
  `QUANTITYMULTIPLE` float(5,2) NOT NULL DEFAULT '1.00',
  `QUANTITYMEASURE` char(16) NOT NULL DEFAULT 'C62',
  `OPTCOUNTER` int(5) DEFAULT NULL,
  PRIMARY KEY (`CATENTRY_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=181 DEFAULT CHARSET=latin1;

CREATE TABLE `listprice` (
  `CATENTRY_ID` bigint(20) NOT NULL,
  `CURRENCY` char(3) NOT NULL,
  `LISTPRICE` float(20,5) NOT NULL,
  `OPTCOUNTER` int(5) DEFAULT NULL,
  PRIMARY KEY (`CATENTRY_ID`,`CURRENCY`),
  KEY `idx_listprice_CATENTRY_ID_CURRENCY_LISTPRICE` (`CATENTRY_ID`,`CURRENCY`,`LISTPRICE`),
  KEY `idx_listprice_CATENTRY_ID` (`CATENTRY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `setcurr` (
  `SETCCURR` char(3) NOT NULL,
  `SETCCODE` int(11) NOT NULL,
  `SETCEXP` int(11) NOT NULL,
  `SETCNOTE` varchar(45) DEFAULT NULL,
  `OPTCOUNTER` int(11) DEFAULT NULL,
  PRIMARY KEY (`SETCCURR`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='The table contains information about the different national ';


